version: "3"
services:
  mount-bookmark:
    image: jokobsk/mount-bookmark
    container_name: mount-bookmark
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - 13003:3000
    volumes:
      - ${APP_DATA_LOCATION}/mount-bookmark/local_artwork/:/opt/mount-bookmark/src/config/local_artwork
      - ${APP_DATA_LOCATION}/mount-bookmark/settings.json:/opt/mount-bookmark/src/config/settings.json
    environment:
      - TZ=Australia/Sydney
      - PUID=1000
      - PGID=1000
